version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbevent
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: eventoapp/eventoapp
    environment:
      DB_HOST: database
    ports:
      - "8080:8080"
volumes:
  db-volume: